// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omojhtskgeonvfwhdrmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tb2podHNrZ2VvbnZmd2hkcm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODIyODIsImV4cCI6MjA2ODI1ODI4Mn0.7sZ35uufKKM-5RUgcnkoZJhFh0iZXjpBHGB9jVb29Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});